name: 100DaysOfPython
channels: 
    - conda-forge
dependencies: 
    - python=3.9
    - jupyterlab=3.0.15
    - matplotlib=3.3.2
    - numpy=1.21.5
    - pandas=1.2.0
    - requests=2.24.0
    - scipy=1.5.2
    - seaborn=0.11.2
    - colorgram.py=1.2.0
